// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbnm3X57a3JMaQtXHYglcsXFCHSUyTWMw',
    appId: '1:987914961227:web:306f46d5e760a3f81568ce',
    messagingSenderId: '987914961227',
    projectId: 'rehana-dc092',
    authDomain: 'rehana-dc092.firebaseapp.com',
    storageBucket: 'rehana-dc092.firebasestorage.app',
    measurementId: 'G-PBDQGE12L8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7EQA91kuiZcqXuHFOpsKNG7tSSif97I4',
    appId: '1:987914961227:ios:4cdc6c3f922a78f61568ce',
    messagingSenderId: '987914961227',
    projectId: 'rehana-dc092',
    storageBucket: 'rehana-dc092.firebasestorage.app',
    iosBundleId: 'com.example.rehanaDashboared',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7EQA91kuiZcqXuHFOpsKNG7tSSif97I4',
    appId: '1:987914961227:ios:4cdc6c3f922a78f61568ce',
    messagingSenderId: '987914961227',
    projectId: 'rehana-dc092',
    storageBucket: 'rehana-dc092.firebasestorage.app',
    iosBundleId: 'com.example.rehanaDashboared',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiqh9r7YgyG8OgFAe9TbkSWHEpVhqT3Mw',
    appId: '1:987914961227:android:36ac38ca9125a9fb1568ce',
    messagingSenderId: '987914961227',
    projectId: 'rehana-dc092',
    storageBucket: 'rehana-dc092.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbnm3X57a3JMaQtXHYglcsXFCHSUyTWMw',
    appId: '1:987914961227:web:7d72654db56603be1568ce',
    messagingSenderId: '987914961227',
    projectId: 'rehana-dc092',
    authDomain: 'rehana-dc092.firebaseapp.com',
    storageBucket: 'rehana-dc092.firebasestorage.app',
    measurementId: 'G-XZLYV0NP52',
  );

}